### ISSUE TITLE
plot_metagenome_contributions.R

### ISSUE THREAD

**Issue by rajansuja** [LangilleLab/microbiome_helper#12]
Is there a way to increase the number of colors while plotting the stacked graph with plot_metagenome_contributions.R? Because right now a set of 12 colors keeps getting repeated to cover all categories within a rank. Please let me know. thanks.

**Comment by gavinmdouglas** [comment]
Those 12 colours are the script’s default, which were chosen since they can be qualitatively distinguished easily. However, you can also use the default R colours with this flag: "—R_default_colours”, which will likely be harder to distinguish, but will use a different colour for each different category.

Best,

Gavin
