### ISSUE TITLE
mammlian blocking primers

### ISSUE THREAD

**Issue by krmaas** [LangilleLab/microbiome_helper#32]
Hi Morgan/et.al.
What blocking mechanism are you using for your blocking primers? Can you share the primer sequence with the codes for the blocking mechanism? Also, how well did these seem to work? I have people asking me to sequence bacteria out of tissue plugs-so very high host/bac DNA and I'm getting >98% mitochondria.
thanks
Kendra

**Comment by amcomeau** [comment]
Kendra,

We have only used so far a mammalian PNA blocking primer (elongation arrest) for the 18S V4 region (sequence in our wet lab protocols: https://github.com/LangilleLab/microbiome_helper/wiki/Microbiome-Amplicon-Sequencing-Workflow) and not yet any 16S blockers, although a client is going to send us a chloroplast one to test (no mtDNA ones here yet).


We found the 18S one worked pretty well on primate DNAs (since full of other Euks), but performed poorly on human stool DNAs due to such a low amount of enteral Euks present in "Western" humans (ie: any 18S that was there was mostly human, so the BP just couldn't keep up). Hopefully you can find something in the literature for a 16S mtDNA one, but remember you need it to be specific to the amplified region you are sequencing (ie: you may not be able to use someone's great already-developed mt blocker if it is not in your V4-V5 region, etc.).



André M. Comeau, PhD
Manager
CGEB - Integrated Microbiome Resource (IMR)
www.cgeb-imr.ca<http://www.cgeb-imr.ca>
Dalhousie University

Research Associate / Lab Manager
Morgan Langille Lab (morganlangille.com<http://morganlangille.com>)
Dept. of Pharmacology
Dalhousie University

Office: 5D-1, 5th floor Tupper Bldg (map<http://goo.gl/maps/4EEb5>)
Phone: (902) 494-3529
Email: andre.comeau@dal.ca
Mailing: 5850 College Street, Halifax NS B3H 4R2

Research profile: www.researchgate.net/profile/Andre_Comeau<http://www.researchgate.net/profile/Andre_Comeau>
Publications: scholar.google.ca/citations?hl=en&user=-K-N4ssAAAAJ<http://scholar.google.ca/citations?hl=en&user=-K-N4ssAAAAJ>

"Without fantasy, there is no science.  Without fact, there is no art."
                      - Nabokov
"The good thing about science is that it's true whether or not you believe in it."
                      - Neil deGrasse Tyson


________________________________

**Comment by krmaas** [comment]
Ah I was reading quickly, thought yours was 16s. I may ask you in the future how the chloroplast one works, I've had one rhizosphere project that resulted in mostly chloroplast when I was just using the "biased against chloroplast" version of v4 primers.
