### ISSUE TITLE
humann2_barplot

### ISSUE THREAD

**Issue by lmanchon** [LangilleLab/microbiome_helper#37]
--Hi,

is there a way to use humann2_barplot command to plot family of species per sample using 'humann2_genefamilies.tsv' file output ?

thank you --

**Comment by gavinmdouglas** [comment]
Hi there,

I believe that script will just plot the stratification for whatever taxa reported by HUMAnN2. Since the breakdown is reported at the species level I don't think there's a simple way to get the breakdown by family level.

I think the only way would be to write your own custom script that would convert the species labels to their respective family level labels. This has likely already been asked on the HUMAnN2 google group however, so I would recommend checking there as well.

Best,

Gavin
