### ISSUE TITLE
Normalizing data obtained from other software?  

### ISSUE THREAD

**Issue by Jigyasa3** [LangilleLab/microbiome_helper#44]
Hey!

Is it possible to incorporate a relative abundance file into humann2 for downstream analysis?
For example, I have an insect gut metagenome data which I have annotated via COG and Pfam database. I also have the taxonomic information via MEGAN package. Furthermore, I have converted the raw counts into reads per million for each function and taxa.

But I want to incorporate the gap-filling step in humann2 and compression constant to account for gene copy number and pathway copy number non-linearity. (https://bitbucket.org/biobakery/humann2/wiki/Home#markdown-header-2-pathway-abundance-file).

I was wondering if there is a "cheat" way of doing these normalizations without re-running the analysis from scratch?

Thanks!

**Comment by gavinmdouglas** [comment]
Hi there,

You can definitely input gene family tables to HUMAnN2 so that you can just run the pathway inference step (and select gap filling) without needing to re-run the entire pipeline from scratch. You might have more luck on the HUMAnN2 forum with specific questions in the future though by the way.


Best,

Gavin

**Comment by Jigyasa3** [comment]
Thank you @gavinmdouglas !
